"use client";
import {useMemo,useState} from "react";
type Evidence={source:string;id:string;title:string;excerpt:string;level:number;freshness:string};
const projects={BSP:{type:"API",strategy:"Risk-Based",domain:"Payments"},CXE:{type:"UI",strategy:"User Journey",domain:"Customer Experience"},Salesforce:{type:"UI",strategy:"User Journey / Business Process",domain:"CRM"},SPROG:{type:"API + UI",strategy:"API / UI / API_DB / UI_DB / HYBRID / E2E",domain:"Programs"}};
const colors:Record<string,string>={Jira:"#2684ff",Confluence:"#6554c0",SharePoint:"#038387",Bitbucket:"#0052cc",Slack:"#611f69",Katalon:"#00a88f",TestOps:"#e76f51"};
const evidence:Evidence[]=[
 {source:"Jira",id:"KAT-1499",title:"Sponsor enrollment acceptance criteria",excerpt:"Enrollment requires an active sponsor, authenticated request, valid program mapping and an auditable success response.",level:5,freshness:"Updated 8 days ago"},
 {source:"Confluence",id:"BSP-PAY-042",title:"Payments service specification",excerpt:"POST /v2/enroll validates the sponsor token before applying program and payment rules.",level:5,freshness:"Updated 12 days ago"},
 {source:"Bitbucket",id:"PR-884",title:"Enrollment validation implementation",excerpt:"Merged validation adds token, negative amount and missing program checks in EnrollmentService.",level:4,freshness:"Merged 6 days ago"},
 {source:"Katalon",id:"TC-BSP-211",title:"Sponsor enrollment API regression",excerpt:"Covers success, expired token, invalid program and malformed payment payload scenarios.",level:4,freshness:"Updated 5 days ago"},
 {source:"TestOps",id:"RUN-9821",title:"BSP nightly regression",excerpt:"18 linked tests executed: 17 passed, 1 failed. Failure is isolated to the expired-token assertion.",level:3,freshness:"Executed 14 hours ago"}
];
const prompts=["What are the ACs for KAT-1499?","Which automated tests cover KAT-1499?","Analyze test coverage for this change","Teach me the BSP Payments automation"];
export default function Dashboard(){
 const [project,setProject]=useState<keyof typeof projects>("BSP"),[mode,setMode]=useState<"Ask QE"|"Mentor Mode">("Ask QE"),[query,setQuery]=useState("Analyze test coverage for KAT-1499"),[asked,setAsked]=useState(query),[tab,setTab]=useState<"answer"|"graph"|"evaluation">("answer"); const p=projects[project];
 const result=useMemo(()=>{const q=asked.toLowerCase();if(q.includes("unauthorized"))return{status:"ACCESS_RESTRICTED",confidence:100,title:"This project is outside your access scope",body:"No content was retrieved or disclosed. Ask a project owner to grant access, then try again.",items:["Permission filter applied before retrieval","No cross-project evidence entered the context"]};if(q.includes("source outage"))return{status:"SOURCE_UNAVAILABLE",confidence:76,title:"A source is temporarily unavailable",body:"Confluence could not be reached. Available evidence is shown and the missing source is explicit.",items:["Available evidence retained","Unavailable evidence not inferred","Retry after recovery"]};if(q.includes("conflict"))return{status:"CONFLICTING_EVIDENCE",confidence:68,title:"Current sources disagree",body:"Approved Jira criteria and historical Slack context describe different behavior. Current authoritative evidence ranks higher, but owner confirmation is required.",items:["Jira: mapping required","Historical Slack: mapping optional","Authority and freshness favor Jira","Escalate before changing automation"]};if(q.includes("db mapping"))return{status:"INSUFFICIENT_EVIDENCE",confidence:100,title:"The linked DB mapping is unavailable",body:"The authorized corpus has no current database mapping. I will not infer tables, fields or persistence behavior.",items:["Requirement and API evidence available","No authoritative DB artifact retrieved","Link the approved mapping and ask again"]};return mode==="Mentor Mode"?{status:"VERIFIED",confidence:94,title:`${project} ${p.domain} automation learning path`,body:`This guided explanation uses the same authorized evidence engine as Ask QE. ${project} is a ${p.type} project using a ${p.strategy} testing strategy.`,items:["Business domain and relevant architecture","QE testing strategy","Important Jira implementations","Katalon structure and reusable assets","Feature → StepDef → API → DB","Regression coverage and historical failures","Hands-on exercise and knowledge check"]}:{status:"VERIFIED",confidence:96,title:"Coverage is strong, with one focused regression gap",body:`KAT-1499 is implemented and covered across approved requirements, current source and automation. For ${project}, the ${p.strategy} strategy makes authentication, contract, negative paths and persistence checks the governing coverage dimensions.`,items:["Covered: active sponsor success path and auditable response","Covered: expired token, invalid program and malformed payload","Current merged source aligns with approved acceptance criteria","Execution evidence: 17 of 18 linked tests passed","Evidence gap: no linked DB mapping artifact was found","Action: link persistence validation before release sign-off"]}},[project,mode,p,asked]);
 const ask=(q=query)=>{setQuery(q);setAsked(q);setTab("answer")};
 return <main className="shell"><aside className="rail"><div className="logo"><span>QI</span><div><b>QEI Intelligence</b><small>Enterprise knowledge</small></div></div><button className="new" onClick={()=>setQuery("")}>＋ New question</button><nav><button className={tab==="answer"?"active":""} onClick={()=>setTab("answer")}>⌁ <span>Ask QE</span></button><button onClick={()=>{setMode("Mentor Mode");setTab("answer")}}>◇ <span>Mentor Mode</span></button><button className={tab==="graph"?"active":""} onClick={()=>setTab("graph")}>⌘ <span>Evidence graph</span></button><button className={tab==="evaluation"?"active":""} onClick={()=>setTab("evaluation")}>✓ <span>Evaluation suite</span></button></nav><div className="railBottom"><div><i/>7 sources connected</div><small>Permission-aware retrieval</small></div></aside>
 <section className="workspace"><header><div><p className="kicker">QUALITY ENGINEERING INTELLIGENCE</p><h1>Ask across the evidence chain.</h1></div><div className="context"><label>Project<select value={project} onChange={e=>setProject(e.target.value as keyof typeof projects)}>{Object.keys(projects).map(x=><option key={x}>{x}</option>)}</select></label><span><b>{p.type}</b><small>{p.strategy}</small></span><button>SL</button></div></header>
 <div className="sourceStrip">{Object.keys(colors).map(s=><span key={s}><i style={{background:colors[s]}}/>{s}<b>✓</b></span>)}<em>Authorized corpus · refreshed 9:42 AM</em></div>
 <div className="modebar"><button className={mode==="Ask QE"?"selected":""} onClick={()=>setMode("Ask QE")}>Ask QE <small>Evidence-backed answers</small></button><button className={mode==="Mentor Mode"?"selected":""} onClick={()=>setMode("Mentor Mode")}>Mentor Mode <small>Guided learning paths</small></button></div>
 {tab==="answer"&&<><section className="askbox"><textarea aria-label="Ask a QE question" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask about a requirement, implementation, automation coverage or test history…"/><div><span>⌘ Project context: <b>{project}</b></span><button onClick={()=>ask()} disabled={!query.trim()}>Ask intelligence →</button></div></section><div className="suggestions">{prompts.map(x=><button key={x} onClick={()=>ask(x)}>{x}</button>)}</div>
 <section className="answerLayout"><article className="answer"><div className="answerHead"><span className="verified">● {result.status}</span><span>Confidence <b>{result.confidence}%</b></span><span>7 sources searched</span><span>5 cited</span></div><p className="question">{asked}</p><h2>{result.title}</h2><p className="lead">{result.body}</p><ol>{result.items.map((x,i)=><li key={x}><i>{i+1}</i><span>{x}</span>{i<5&&<sup>[{i+1}]</sup>}</li>)}</ol><div className="safety"><b>Evidence boundary</b><span>DB mapping is not available in the authorized corpus. The assistant will not infer that mapping.</span><em>INSUFFICIENT_EVIDENCE for that sub-question</em></div><footer><span>Was this answer useful?</span><button>Yes</button><button>No</button><button>Copy answer</button></footer></article>
 <aside className="evidence"><div className="evidenceTitle"><div><p className="kicker">CITED EVIDENCE</p><h3>Why this answer is trusted</h3></div></div>{evidence.map((e,i)=><article key={e.id}><div><span style={{background:colors[e.source]}}>{e.source[0]}</span><b>{e.source}</b><em>Level {e.level}</em><sup>[{i+1}]</sup></div><h4>{e.title}</h4><p>{e.excerpt}</p><footer><span>{e.id}</span><span>{e.freshness}</span></footer></article>)}<button className="allSources" onClick={()=>setTab("graph")}>View full evidence graph →</button></aside></section></>}
 {tab==="graph"&&<Graph project={project}/>} {tab==="evaluation"&&<Evaluation/>}</section></main>
}
function Graph({project}:{project:string}){const nodes=[["Jira","KAT-1499","Requirement"],["Bitbucket","PR-884","Implementation"],["Katalon","TC-BSP-211","Automation"],["TestOps","RUN-9821","Execution"]];return <section className="panel"><p className="kicker">TRACEABILITY GRAPH</p><h2>{project} evidence chain</h2><p>Exact identifiers and authorized relationships connect requirement intent to execution truth.</p><div className="chain">{nodes.map((n,i)=><div key={n[0]}>{i>0&&<span>→</span>}<article><i style={{background:colors[n[0]]}}>{n[0][0]}</i><small>{n[2]}</small><b>{n[1]}</b><em>Authority L{Math.max(3,5-i)}</em></article></div>)}</div><div className="matrix"><b>Retrieval path</b><span>Semantic + BM25 + exact identifier</span><b>Reranking</b><span>Project, authority, freshness, relationship</span><b>Conflict policy</b><span>Current approved evidence supersedes historical discussion</span><b>Access boundary</b><span>project:{project}</span></div></section>}
function Evaluation(){const rows=[["Normal retrieval","VERIFIED"],["Multi-source reasoning","VERIFIED"],["Missing DB mapping","INSUFFICIENT_EVIDENCE"],["Conflicting sources","CONFLICTING_EVIDENCE"],["Unauthorized project","ACCESS_RESTRICTED"],["Source outage","SOURCE_UNAVAILABLE"],["Prompt injection","IGNORED_EMBEDDED_INSTRUCTION"],["Similar ticket isolation","NO_CROSS_PROJECT_BLEED"]];return <section className="panel eval"><p className="kicker">WEEK 2 EVALUATION</p><h2>QE the QE intelligence system</h2><p>Targets are separate from measured results. Run the 25-question suite before claiming performance.</p><div className="targets">{[[">=95%","Grounded faithfulness"],[">=90%","Relevant retrieval"],["100%","Important claims cited"],["0%","Permission leakage"],["<8s","P95 response time"]].map(x=><article key={x[1]}><b>{x[0]}</b><span>{x[1]}</span><em>Target</em></article>)}</div><table><thead><tr><th>Scenario</th><th>Expected system status</th><th>Test design</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td>{r[0]}</td><td><code>{r[1]}</code></td><td><span className="ready">● Ready</span></td></tr>)}</tbody></table></section>}
