"use client";
import {useEffect,useRef,useState} from "react";
import {sampleData} from "./sample-data";
import {summarizeCsv,type DashboardSummary} from "../lib/csv-metrics";

const n=(x:number)=>x.toLocaleString("en-US"),date=(x:string)=>new Date(`${x}T00:00:00Z`).toLocaleDateString("en-US",{month:"short",day:"numeric",timeZone:"UTC"}),mins=(s:number)=>s>=60?`${Math.round(s/60)}m`:`${s}s`;
export default function Dashboard(){
 const [data,setData]=useState<DashboardSummary>(sampleData),[project,setProject]=useState<string|null>(null),[importOpen,setImportOpen]=useState(false),[importing,setImporting]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{fetch("/api/imports").then(r=>r.ok?r.json():null).then(x=>x&&setData(x)).catch(()=>{})},[]);
 const doImport=async(file?:File)=>{if(!file)return;setError("");setImporting(true);try{const text=await file.text();const preview=summarizeCsv(text,file.name);const form=new FormData();form.append("file",file);const response=await fetch("/api/imports",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error||"Import failed");setData(result||preview);setImportOpen(false);setNotice(`${file.name} imported · ${n(preview.rowCount)} rows`);setTimeout(()=>setNotice(""),5000)}catch(e){setError(e instanceof Error?e.message:"Import failed")}finally{setImporting(false)}};
 const best=[...data.projects].sort((a,b)=>b.rate-a.rate)[0],watch=[...data.projects].sort((a,b)=>a.rate-b.rate)[0],maxVolume=Math.max(...data.projects.map(p=>p.executed),1),maxGrowth=Math.max(...data.weeks.map(w=>w.newTests),1);
 const kpis=[{label:"Automated tests",value:n(data.totalTests),delta:`${data.growthPercent>=0?"+":""}${data.growthPercent}%`,note:"weekly growth",icon:"▤"},{label:"New tests",value:`+${data.newThisWeek}`,delta:data.newLastWeek?`${Math.round((data.newThisWeek-data.newLastWeek)/data.newLastWeek*100)}%`:"—",note:`${data.newLastWeek} last week`,icon:"+"},{label:"Pass rate",value:`${data.passRate}%`,delta:`${data.passRateChange>=0?"+":""}${data.passRateChange} pts`,note:"vs prior 30 days",icon:"✓"},{label:"Test runs",value:n(data.runs),delta:`${data.executionChange>=0?"+":""}${data.executionChange}%`,note:"execution volume",icon:"▶"}];
 return <main>
  <aside><div className="brand"><b>K</b><span><strong>TestOps</strong><small>Automation intelligence</small></span></div><nav>{[["⌂","Overview"],["↗","Automation growth"],["◎","Execution health"],["▦","Projects"],["◇","Stability"],["!","Failure analysis"]].map((x,i)=><a className={i===0?"on":""} href={`#${i}`} key={x[1]}><i>{x[0]}</i>{x[1]}</a>)}</nav><div className="sync"><i/><span><b>CSV source active</b><small>{n(data.rowCount)} validated rows</small></span></div></aside>
  <section className="page">
   <header><div><p className="eyebrow">QUALITY ENGINEERING / PORTFOLIO</p><h1>Automation health</h1><p>Coverage, quality and execution from your Katalon TestOps reporting source.</p></div><div className="actions"><button onClick={()=>window.print()}>⇩ Export</button><button className="importBtn" onClick={()=>setImportOpen(true)}>＋ Import CSV</button><button className="primary" onClick={()=>location.reload()}>↻ Refresh data</button></div></header>
   {notice&&<div className="toast">✓ {notice}</div>}
   <div className="status"><b className={data.passRate>=95?"":"yellowStatus"}><i/> Portfolio health: {data.passRate>=95?"Green":data.passRate>=90?"Yellow":"Red"}</b><span className="sourcePill">CSV</span><strong>{data.source}</strong><span>{date(data.periodStart)} – {date(data.periodEnd)} · last 30 days</span><button onClick={()=>setImportOpen(true)}>Manage data source →</button></div>
   <section className="kpis">{kpis.map((k,i)=><article className="card kpi" key={k.label}><div><span>{k.label}</span><i className={`ki c${i}`}>{k.icon}</i></div><strong>{k.value}</strong><p><b className={(i===2&&data.passRateChange<0)?"bad":""}>{i===2&&data.passRateChange<0?"↓":"↑"} {k.delta}</b> {k.note}</p></article>)}</section>
   <section className="grid wide" id="1"><article className="card growth"><Title over="AUTOMATION GROWTH" title="New tests added per week" extra={<span className="legend">■ New tests　━ Cumulative</span>}/><div className="metric"><b>+{data.newThisWeek}</b><span>this week</span><em>{data.newThisWeek===0?"No new tests":"Growth recorded"}</em></div><div className="bars">{data.weeks.map(w=><div key={w.week}><span>{w.newTests}</span><i style={{height:Math.max(3,w.newTests/maxGrowth*92)}} title={`${w.cumulativeTests} cumulative`}/><small>{date(w.week)}</small></div>)}</div></article>
    <article className="card distribution"><Title over="EXECUTION HEALTH" title="Result distribution"/><div className="donut" style={{background:`conic-gradient(#29a36f 0 ${data.passed/data.executed*100}%,#ea5a66 0 ${(data.passed+data.failed)/data.executed*100}%,#e8ac39 0)`}}><span><b>{n(data.executed)}</b><small>tests executed</small></span></div><div className="results">{[["Passed",data.passed,`${Math.round(data.passed/data.executed*1000)/10}%`,"green"],["Failed",data.failed,`${Math.round(data.failed/data.executed*1000)/10}%`,"red"],["Skipped",data.skipped,`${Math.round(data.skipped/data.executed*1000)/10}%`,"amber"]].map(x=><div key={x[0]}><span><i className={String(x[3])}/>{x[0]}</span><b>{n(Number(x[1]))}</b><em>{x[2]}</em></div>)}</div></article>
   </section>
   <section className="grid wide second" id="2"><article className="card"><Title over="PASS RATE TREND" title="Weekly execution quality" extra={<span className="target">Target 95%</span>}/><div className="linechart"><div className="targetline">95%</div><div className="stroke"/>{data.weeks.map((w,i)=><i key={w.week} style={{left:`${5+i*(90/Math.max(data.weeks.length-1,1))}%`,bottom:`${Math.max(8,20+(w.passRate-90)*13)}px`}} title={`${w.passRate}%`}/>)}</div><div className="labels">{data.weeks.map(w=><small key={w.week}>{date(w.week)}</small>)}</div></article>
    <article className="card volume"><Title over="EXECUTION VOLUME" title="Tests executed" extra={<span className="good">{data.executionChange>=0?"↑":"↓"} {Math.abs(data.executionChange)}%</span>}/><div className="metric"><b>{n(data.executed)}</b><span>last 30 days</span></div>{data.projects.map((p,i)=><div className="progress" key={p.name}><span>{p.name}</span><i><b className={["purple","blue","teal","orange"][i%4]} style={{width:`${p.executed/maxVolume*94}%`}}/></i><strong>{n(p.executed)}</strong></div>)}</article>
   </section>
   <section className="card projects" id="3"><Title over="PROJECT PERFORMANCE" title="Portfolio overview" extra={<span className="periodNote">Source: {data.source}</span>}/><div className="table"><table><thead><tr>{["Project","Automated tests","New this week","Tests executed","Passed","Failed","Pass rate","Avg duration","Status"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.projects.map(p=><tr key={p.name} onClick={()=>setProject(p.name)}><td><i>{p.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</i><b>{p.name}</b></td><td>{p.tests}</td><td className="good">+{p.added}</td><td>{n(p.executed)}</td><td>{n(p.passed)}</td><td>{p.failed}</td><td><b>{p.rate}%</b><span className="track"><i className={p.rate>=95?"green":"amber"} style={{width:`${p.rate}%`}}/></span></td><td>{mins(p.avgDurationSeconds)}</td><td><span className={`health ${p.rate>=95?"healthy":"watch"}`}><i/>{p.rate>=95?"Healthy":"Watch"}</span></td></tr>)}</tbody></table></div></section>
   <section className="failGrid" id="5"><article className="card failureTable"><Title over="FAILURE ANALYSIS" title="Top failing tests" extra={<span className="periodNote">{data.repeatFailures} repeat failures</span>}/>{data.failures.map(f=><div className="failureRow" key={`${f.project}-${f.testCase}`}><span><b>{f.testCase}</b><small>{f.project} · {f.category}</small></span><strong>{f.failures} failures</strong><em>{date(f.lastFailure)}</em></div>)}</article><article className="card sourceCard"><Title over="DATA SOURCE" title="Current import"/><div className="fileBadge">CSV</div><b>{data.source}</b><p>{n(data.rowCount)} rows · {data.projects.length} projects<br/>{date(data.periodStart)} through {date(data.periodEnd)}</p><button onClick={()=>setImportOpen(true)}>Import next month’s CSV</button></article></section>
   <section className="bottom" id="4"><article className="card summary"><p className="eyebrow">WEEKLY MANAGEMENT SUMMARY</p><h2>Automation health is {data.passRate>=95?"strong":"stable with attention needed"}</h2><p>The portfolio contains <b>{n(data.totalTests)} automated tests</b>. Pass rate is <b>{data.passRate}%</b> across {n(data.executed)} executions in the reporting window. {data.newThisWeek?`${data.newThisWeek} new tests were added this week.`:"No new tests were added this week."}</p><div><span><small>BEST PERFORMING</small><b>{best?.name} · {best?.rate}%</b></span><span><small>REQUIRES ATTENTION</small><b>{watch?.name} · {watch?.rate}%</b></span></div></article>{[["◇","Flaky tests",data.flaky,`${data.repeatFailures} repeat failures`],["!","Failed tests",data.failed,`${data.failed/data.executed*100|0}% of results`],["◷","Avg duration",mins(data.avgDurationSeconds),`${mins(data.shortestDurationSeconds)} – ${mins(data.longestDurationSeconds)}`]].map((x,i)=><article className="card mini" key={x[1]}><i className={`m${i}`}>{x[0]}</i><span><small>{x[1]}</small><b>{x[2]}</b><em className={i===1?"bad":"good"}>{x[3]}</em></span></article>)}</section>
  </section>
  {importOpen&&<div className="backdrop"><article className="modal importModal"><button onClick={()=>setImportOpen(false)}>×</button><p className="eyebrow">CSV DATA SOURCE</p><h2>Import monthly TestOps data</h2><p>Upload the next CSV export using the same Katalon column structure. The dashboard validates required fields, prevents a broken import, recalculates every metric and saves the import for future visits.</p><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();doImport(e.dataTransfer.files[0])}} onClick={()=>input.current?.click()}><span>⇧</span><b>{importing?"Importing and calculating…":"Drop a CSV here or browse"}</b><small>CSV only · up to 5 MB · monthly files can include prior history</small><input ref={input} type="file" accept=".csv,text/csv" hidden onChange={e=>doImport(e.target.files?.[0])}/></div>{error&&<p className="importError">{error}</p>}<div className="requirements"><b>Required columns</b><span>execution_id · run_id · project_name · test_case_id · test_case_created_at · execution_started_at · status · duration_seconds</span></div></article></div>}
  {project&&<div className="backdrop" onClick={()=>setProject(null)}><article className="modal" onClick={e=>e.stopPropagation()}><button onClick={()=>setProject(null)}>×</button><p className="eyebrow">PROJECT DRILL-DOWN</p><h2>{project}</h2><p>Metrics shown here are calculated from {data.source}.</p><div><b>Organization</b> → <b>{project}</b> → Test suites → Executions</div><button className="primary">Open project dashboard</button></article></div>}
 </main>
}
function Title({over,title,extra}:{over:string,title:string,extra?:React.ReactNode}){return <div className="title"><div><p className="eyebrow">{over}</p><h2>{title}</h2></div>{extra}</div>}
